twig:
    file_name_pattern: '*.twig'
    globals:
        author: Brendan Tuckerman
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
when@test:
    twig:
        strict_variables: true
